### ISSUE TITLE
Thanks for the sponsorship!

### ISSUE THREAD

**Issue by georgemandis** [appatalks/appatalks#2]
Just wanted to say thanks! :)

I'm slightly curious what project and/or trail of internet breadcrumbs I've left out there that led you to that idea...

But thank you all the same!

Best,
George

**Comment by appatalks** [comment]
> I'm slightly curious what project and/or trail of internet breadcrumbs I've left out there that led you to that idea...

Oh! I've been using your [Konami-js](https://github.com/georgemandis/konami-js) for years now! Pretty much in all my websites someplace or other. 

Thank you for the reachout!
